### ISSUE TITLE
Fix issues with Taxbit csv

### ISSUE THREAD

**Issue by jhicken** [jhicken/crypto-to-csv#1]
I am chatting with support about why my exported csv wont upload correctly

**Comment by Aaronius** [comment]
I see you!

**Comment by jhicken** [comment]
Lol @Aaronius!! been a while. You know how to fix this problem right? :)  JK JK. We aren't on any of the same chat mediums are we?

**Comment by Aaronius** [comment]
LOL. I wish I knew how to fix the problem! I hope our support team gets you sorted out though. No shared chat mediums. 😢

**Comment by jhicken** [comment]
When Importing transactions on taxbit if the fee amount is 0 or null the fee currency should also be null/empty.  Also when the address in question is the receiver sending source should be null.
